import { CivicServiceDefinition, CivicOutputMode } from "@/types/civic.types";

/**
 * Master Registry 18 Dinas Pemkot Surakarta & Pemetaan Moda Output Layanan
 */
export const CIVIC_SERVICES_CATALOG: Record<string, CivicServiceDefinition> = {
  // 1. DISDUKCAPIL (Output: delivery)
  dukcapil_antar_ktp: {
    id: "dukcapil_antar_ktp",
    name: "Dukcapil Antar KTP-el ke Rumah Warga",
    shortName: "Antar KTP-el",
    agencyId: "gov_dukcapil",
    agencyName: "Dinas Kependudukan & Pencatatan Sipil",
    outputMode: "delivery",
    slaMinutes: 120,
    feeLabel: "Gratis Pengantaran (Subsidi Pemkot)",
    price: 0,
    description: "Pengantaran fisik KTP-el resmi ke rumah warga via mitra kurir ber-OTP.",
    requiresDeliveryAddress: true,
    requiresAttachments: true,
    isEmergency: false,
  },
  dukcapil_kia_akte: {
    id: "dukcapil_kia_akte",
    name: "Pengantaran KIA & Akta Kelahiran/Kematian",
    shortName: "KIA & Akta",
    agencyId: "gov_dukcapil",
    agencyName: "Dinas Kependudukan & Pencatatan Sipil",
    outputMode: "delivery",
    slaMinutes: 180,
    feeLabel: "Gratis Layanan",
    price: 0,
    description: "Pengantaran dokumen KIA dan kutipan akta kelahiran/kematian langsung ke alamat pemohon.",
    requiresDeliveryAddress: true,
    requiresAttachments: true,
    isEmergency: false,
  },
  dukcapil_mobile_perekaman: {
    id: "dukcapil_mobile_perekaman",
    name: "Layanan Perekaman KTP-el Mobile (Lansia/Difabel)",
    shortName: "Perekaman Mobile",
    agencyId: "gov_dukcapil",
    agencyName: "Dinas Kependudukan & Pencatatan Sipil",
    outputMode: "field_visit",
    slaMinutes: 240,
    feeLabel: "Gratis Layanan Jemput Bola",
    price: 0,
    description: "Petugas Dukcapil datang ke rumah untuk perekaman biometrik lansia dan warga sakit.",
    requiresDeliveryAddress: true,
    requiresAttachments: false,
    isEmergency: false,
  },

  // 2. DINAS KESEHATAN (Output: delivery / emergency_dispatch)
  dinkes_resep_obat: {
    id: "dinkes_resep_obat",
    name: "Pengantaran Obat Resep Puskesmas & RSUD",
    shortName: "Antar Obat Resep",
    agencyId: "gov_dinkes",
    agencyName: "Dinas Kesehatan Kota Surakarta",
    outputMode: "delivery",
    slaMinutes: 90,
    feeLabel: "Gratis Pengantaran Medis",
    price: 0,
    description: "Pengantaran obat resep dari apotek Puskesmas langsung ke pasien dengan segel farmasi.",
    requiresDeliveryAddress: true,
    requiresAttachments: true,
    isEmergency: false,
  },
  dinkes_prolanis: {
    id: "dinkes_prolanis",
    name: "Distribusi Obat Rutin Prolanis BPJS",
    shortName: "Obat Prolanis",
    agencyId: "gov_dinkes",
    agencyName: "Dinas Kesehatan Kota Surakarta",
    outputMode: "delivery",
    slaMinutes: 120,
    feeLabel: "Gratis Peserta Prolanis",
    price: 0,
    description: "Distribusi bulanan obat hipertensi & diabetes bagi peserta Prolanis.",
    requiresDeliveryAddress: true,
    requiresAttachments: true,
    isEmergency: false,
  },
  dinkes_donor_darah: {
    id: "dinkes_donor_darah",
    name: "Armada Siaga Kurir Darah PMI & Faskes",
    shortName: "Kurir Darah PMI",
    agencyId: "gov_dinkes",
    agencyName: "Dinas Kesehatan Kota Surakarta",
    outputMode: "emergency_dispatch",
    slaMinutes: 30,
    feeLabel: "Siaga Darurat 24 Jam",
    price: 0,
    description: "Pengantaran kantong darah darurat dari UDD PMI ke rumah sakit rujukan.",
    requiresDeliveryAddress: true,
    requiresAttachments: false,
    isEmergency: true,
  },

  // 3. DINAS SOSIAL (Output: subsidy_voucher / delivery)
  dinsos_bansos_sembako: {
    id: "dinsos_bansos_sembako",
    name: "Voucher Bansos Sembako di Pasar Tradisional",
    shortName: "Voucher Sembako",
    agencyId: "gov_dinsos",
    agencyName: "Dinas Sosial Kota Surakarta",
    outputMode: "subsidy_voucher",
    slaMinutes: 60,
    feeLabel: "Subsidi Pangan Pemkot",
    price: 0,
    description: "Penerbitan barcode voucher digital untuk pengambilan bahan pangan di pasar tradisional.",
    requiresDeliveryAddress: false,
    requiresAttachments: true,
    isEmergency: false,
  },
  dinsos_ojek_difabel: {
    id: "dinsos_ojek_difabel",
    name: "Layanan Antar Jemput Warga Difabel & Lansia",
    shortName: "Antar Jemput Difabel",
    agencyId: "gov_dinsos",
    agencyName: "Dinas Sosial Kota Surakarta",
    outputMode: "delivery",
    slaMinutes: 45,
    feeLabel: "Subsidi Penuh 100%",
    price: 0,
    description: "Penugasan armada ramah difabel untuk mengantar warga ke faskes / sentra pelayanan.",
    requiresDeliveryAddress: true,
    requiresAttachments: false,
    isEmergency: false,
  },
  dinsos_tanggap_bencana: {
    id: "dinsos_tanggap_bencana",
    name: "Posko Tanggap Bencana & Dapur Umum",
    shortName: "Logistik Dapur Umum",
    agencyId: "gov_dinsos",
    agencyName: "Dinas Sosial Kota Surakarta",
    outputMode: "emergency_dispatch",
    slaMinutes: 30,
    feeLabel: "Siaga Darurat",
    price: 0,
    description: "Penyaluran cepat ransum dan bantuan logistik darurat ke lokasi pengungsian.",
    requiresDeliveryAddress: true,
    requiresAttachments: false,
    isEmergency: true,
  },

  // 4. DINAS KOPERASI & UMKM (Output: digital_issuance / subsidy_voucher)
  diskop_legalitas_nib: {
    id: "diskop_legalitas_nib",
    name: "Penerbitan Sertifikasi Legalitas & NIB OSS UMKM",
    shortName: "Sertifikat NIB OSS",
    agencyId: "gov_diskop",
    agencyName: "Dinas Koperasi & UKM Kota Surakarta",
    outputMode: "digital_issuance",
    slaMinutes: 1440, // 24 Jam
    feeLabel: "Gratis Fasilitasi Pemkot",
    price: 0,
    description: "Penerbitan Surat Rekomendasi & Sertifikat NIB OSS resmi ber-QR Code bagi pelaku usaha mikro.",
    requiresDeliveryAddress: false,
    requiresAttachments: true,
    isEmergency: false,
  },
  diskop_dana_bergulir: {
    id: "diskop_dana_bergulir",
    name: "Klaim Subsidi Karcis Harian & SHU Koperasi",
    shortName: "Klaim SHU Koperasi",
    agencyId: "gov_diskop",
    agencyName: "Dinas Koperasi & UKM Kota Surakarta",
    outputMode: "subsidy_voucher",
    slaMinutes: 120,
    feeLabel: "Koperasi Warga Solo",
    price: 0,
    description: "Penerbitan token klaim dividen SHU atau subsidi pembebasan karcis driver mitra.",
    requiresDeliveryAddress: false,
    requiresAttachments: false,
    isEmergency: false,
  },

  // 5. DAMKAR (Output: emergency_dispatch)
  damkar_pemadaman: {
    id: "damkar_pemadaman",
    name: "Siaga Tanggap Darurat Kebakaran & Evakuasi",
    shortName: "Darurat Kebakaran 113",
    agencyId: "gov_damkar",
    agencyName: "Dinas Pemadam Kebakaran",
    outputMode: "emergency_dispatch",
    slaMinutes: 15,
    feeLabel: "Siaga Darurat 24 Jam",
    price: 0,
    description: "Disposisi armada mobil pemadam dan regu penyelamat ke koordinat laporan kebakaran.",
    requiresDeliveryAddress: true,
    requiresAttachments: false,
    isEmergency: true,
  },

  // 6. BPBD (Output: emergency_dispatch)
  bpbd_lapor_banjir: {
    id: "bpbd_lapor_banjir",
    name: "Lapor Bencana Banjir & Pohon Tumbang",
    shortName: "Siaga Bencana BPBD",
    agencyId: "gov_bpbd",
    agencyName: "Badan Penanggulangan Bencana Daerah",
    outputMode: "emergency_dispatch",
    slaMinutes: 20,
    feeLabel: "Siaga Reaksi Cepat",
    price: 0,
    description: "Penerjunan regu perahu karet evakuasi dan gergaji mesin penanganan pohon tumbang.",
    requiresDeliveryAddress: true,
    requiresAttachments: true,
    isEmergency: true,
  },

  // 7. BAPENDA (Output: digital_issuance)
  bapenda_pbb: {
    id: "bapenda_pbb",
    name: "Layanan Pembayaran PBB-P2 & e-SPPT Digital",
    shortName: "e-SPPT PBB Digital",
    agencyId: "gov_bapenda",
    agencyName: "Badan Pendapatan Daerah",
    outputMode: "digital_issuance",
    slaMinutes: 60,
    feeLabel: "Resmi Bapenda Solo",
    price: 0,
    description: "Penerbitan bukti lunas e-SPPT PBB ber-QR Code resmi tervalidasi perbankan.",
    requiresDeliveryAddress: false,
    requiresAttachments: true,
    isEmergency: false,
  },
  bapenda_retribusi_pasar: {
    id: "bapenda_retribusi_pasar",
    name: "E-Retribusi Kios & Los Pasar Tradisional",
    shortName: "E-Retribusi Pasar",
    agencyId: "gov_bapenda",
    agencyName: "Badan Pendapatan Daerah",
    outputMode: "digital_issuance",
    slaMinutes: 60,
    feeLabel: "Kas Daerah Pemkot",
    price: 0,
    description: "Penerbitan tanda bukti setoran retribusi kios pasar resmi dengan stempel digital.",
    requiresDeliveryAddress: false,
    requiresAttachments: false,
    isEmergency: false,
  },

  // 8. DISKOMINFO (Output: civic_ticket)
  diskominfo_ulas: {
    id: "diskominfo_ulas",
    name: "Layanan Tiket Pengaduan Warga ULAS",
    shortName: "Tiket Aduan ULAS",
    agencyId: "gov_diskominfo",
    agencyName: "Dinas Komunikasi, Informatika, Statistik & Persandian",
    outputMode: "civic_ticket",
    slaMinutes: 180,
    feeLabel: "Layanan Publik 24 Jam",
    price: 0,
    description: "Penerbitan nomor tiket aduan masyarakat terintegrasi sistem satu pintu ULAS Surakarta.",
    requiresDeliveryAddress: false,
    requiresAttachments: true,
    isEmergency: false,
  },

  // 9. DPMPTSP (Output: digital_issuance)
  dpmptsp_mpp_izin: {
    id: "dpmptsp_mpp_izin",
    name: "Penerbitan Rekomendasi Izin Usaha MPP",
    shortName: "Rekomendasi Izin MPP",
    agencyId: "gov_dpmptsp",
    agencyName: "Dinas Penanaman Modal & Pelayanan Terpadu Satu Pintu",
    outputMode: "digital_issuance",
    slaMinutes: 1440,
    feeLabel: "Pelayanan Terpadu Satu Pintu",
    price: 0,
    description: "Penerbitan surat rekomendasi teknis izin usaha ber-QR Code Mal Pelayanan Publik (MPP).",
    requiresDeliveryAddress: false,
    requiresAttachments: true,
    isEmergency: false,
  },

  // 10. DP3A (Output: field_visit)
  dp3a_sapa129: {
    id: "dp3a_sapa129",
    name: "Layanan Pengaduan SAPA 129 & Konseling PUSPAGA",
    shortName: "Konseling SAPA 129",
    agencyId: "gov_dp3a",
    agencyName: "Dinas Pemberdayaan Perempuan & Perlindungan Anak",
    outputMode: "field_visit",
    slaMinutes: 60,
    feeLabel: "Kerahasiaan Identitas Dijamin 100%",
    price: 0,
    description: "Pendampingan konselor keluarga, psikolog klinis, dan tim advokasi ke rumah aman.",
    requiresDeliveryAddress: true,
    requiresAttachments: false,
    isEmergency: true,
  },

  // 11. SATPOL PP (Output: emergency_dispatch)
  satpolpp_trantib: {
    id: "satpolpp_trantib",
    name: "Lapor Gangguan Trantibum & Patroli Cepat",
    shortName: "Patroli Trantibum",
    agencyId: "gov_satpolpp",
    agencyName: "Satuan Polisi Pamong Praja",
    outputMode: "emergency_dispatch",
    slaMinutes: 25,
    feeLabel: "Siaga 24 Jam",
    price: 0,
    description: "Penerjunan regu patroli motor reaksi cepat untuk penanganan ketertiban umum.",
    requiresDeliveryAddress: true,
    requiresAttachments: true,
    isEmergency: true,
  },

  // 12. DISPUSIP (Output: delivery)
  dispusip_kurir_buku: {
    id: "dispusip_kurir_buku",
    name: "Layanan Antar Pinjam Buku Perpustakaan",
    shortName: "Antar Pinjam Buku",
    agencyId: "gov_dispusip",
    agencyName: "Dinas Kearsipan & Perpustakaan",
    outputMode: "delivery",
    slaMinutes: 120,
    feeLabel: "Gratis Pinjam Literasi",
    price: 0,
    description: "Peminjaman dan pengantaran koleksi buku perpustakaan daerah langsung ke alamat warga.",
    requiresDeliveryAddress: true,
    requiresAttachments: false,
    isEmergency: false,
  },

  // 13. DISNAKER (Output: digital_issuance)
  disnaker_kartu_kuning: {
    id: "disnaker_kartu_kuning",
    name: "Penerbitan Kartu Pencari Kerja AK-1 Digital",
    shortName: "Kartu Kuning AK-1",
    agencyId: "gov_disnaker",
    agencyName: "Dinas Tenaga Kerja",
    outputMode: "digital_issuance",
    slaMinutes: 120,
    feeLabel: "Gratis Resmi Disnaker",
    price: 0,
    description: "Penerbitan kartu AK-1 digital ber-QR Code resmi untuk melamar pekerjaan.",
    requiresDeliveryAddress: false,
    requiresAttachments: true,
    isEmergency: false,
  },

  // 14. DISPERTAN (Output: field_visit)
  dispertan_puskeswan: {
    id: "dispertan_puskeswan",
    name: "Layanan Kunjungan Medis Dokter Hewan Puskeswan",
    shortName: "Dokter Hewan Puskeswan",
    agencyId: "gov_dispertan",
    agencyName: "Dinas Pertanian, Ketahanan Pangan & Perikanan",
    outputMode: "field_visit",
    slaMinutes: 180,
    feeLabel: "Pelayanan Hewan Ternak & Peliharaan",
    price: 0,
    description: "Kunjungan dokter hewan Puskeswan Solo untuk vaksinasi rabies dan pengobatan ternak.",
    requiresDeliveryAddress: true,
    requiresAttachments: false,
    isEmergency: false,
  },

  // 15. DLH (Output: field_visit)
  dlh_bank_sampah: {
    id: "dlh_bank_sampah",
    name: "Penjemputan Sampah Terpilah & Bank Sampah",
    shortName: "Jemput Bank Sampah",
    agencyId: "gov_dlh",
    agencyName: "Dinas Lingkungan Hidup",
    outputMode: "field_visit",
    slaMinutes: 240,
    feeLabel: "Solo Bebas Sampah",
    price: 0,
    description: "Penugasan armada gerobak motor DLH untuk menjemput anorganik terpilah bernilai ekonomi.",
    requiresDeliveryAddress: true,
    requiresAttachments: false,
    isEmergency: false,
  },

  // 16. DISHUB (Output: civic_ticket)
  dishub_booking_kir: {
    id: "dishub_booking_kir",
    name: "Booking Antrean Uji Kendaraan Bermotor (KIR)",
    shortName: "Booking Uji KIR",
    agencyId: "gov_dishub",
    agencyName: "Dinas Perhubungan",
    outputMode: "civic_ticket",
    slaMinutes: 60,
    feeLabel: "Retribusi Resmi Dishub",
    price: 0,
    description: "Penerbitan barcode e-KIR dan slot nomor antrean uji berkala kendaraan.",
    requiresDeliveryAddress: false,
    requiresAttachments: true,
    isEmergency: false,
  },

  // 17. DISDIK (Output: delivery)
  disdik_antar_ijazah: {
    id: "disdik_antar_ijazah",
    name: "Legalitas & Pengantaran Dokumen Ijazah",
    shortName: "Legalitas Ijazah",
    agencyId: "gov_disdik",
    agencyName: "Dinas Pendidikan",
    outputMode: "delivery",
    slaMinutes: 180,
    feeLabel: "Pelayanan Pendidikan",
    price: 0,
    description: "Legalisir dan pengantaran salinan ijazah/rapor resmi ke rumah siswa/alumni.",
    requiresDeliveryAddress: true,
    requiresAttachments: true,
    isEmergency: false,
  },

  // 18. DISPAR (Output: civic_ticket)
  dispar_heritage_tour: {
    id: "dispar_heritage_tour",
    name: "Reservasi Pemandu Wisata & Solo Heritage Tour",
    shortName: "Heritage Tour Solo",
    agencyId: "gov_dispar",
    agencyName: "Dinas Kebudayaan & Pariwisata",
    outputMode: "civic_ticket",
    slaMinutes: 120,
    feeLabel: "Pariwisata Kota Surakarta",
    price: 0,
    description: "Penerbitan e-voucher pemandu wisata bersertifikasi HPI dan rute wisata sejarah Solo.",
    requiresDeliveryAddress: false,
    requiresAttachments: false,
    isEmergency: false,
  },

  // 19. DISDAG (Output: subsidy_voucher / delivery)
  disdag_pasar_murah: {
    id: "disdag_pasar_murah",
    name: "Gerakan Pangan Murah (GPM) & Sembako Subsidi SPHP",
    shortName: "Pasar Murah SPHP",
    agencyId: "gov_disdag",
    agencyName: "Dinas Perdagangan",
    outputMode: "subsidy_voucher",
    slaMinutes: 60,
    feeLabel: "Subsidi APBD & BULOG",
    price: 0,
    description: "Penebusan paket sembako beras SPHP, minyakita, dan gula pasir harga HET bersubsidi untuk warga KTP Solo.",
    requiresDeliveryAddress: true,
    requiresAttachments: false,
    isEmergency: false,
  },
};

/**
 * Helper untuk mengambil metadata layanan berdasarkan serviceId
 */
export function getCivicServiceDefinition(serviceId: string): CivicServiceDefinition {
  if (CIVIC_SERVICES_CATALOG[serviceId]) {
    return CIVIC_SERVICES_CATALOG[serviceId];
  }

  // Fallback generic definition
  return {
    id: serviceId,
    name: serviceId.replace(/_/g, " ").toUpperCase(),
    shortName: serviceId,
    agencyId: "gov_solo",
    agencyName: "Pemerintah Kota Surakarta",
    outputMode: "digital_issuance",
    slaMinutes: 120,
    feeLabel: "Resmi Pemkot Surakarta",
    price: 0,
    description: "Pelayanan Publik Terpadu Pemerintah Kota Surakarta.",
    requiresDeliveryAddress: false,
    requiresAttachments: false,
    isEmergency: false,
  };
}
