import { 
  Bike, 
  Car, 
  Package, 
  UtensilsCrossed, 
  Users2, 
  Zap, 
  ShoppingBag, 
  LayoutGrid,
  FileCheck2,
  HeartHandshake,
  Stethoscope,
  Calendar,
  Coins,
  TrafficCone,
  FlaskConical,
  Bus,
  Truck,
  Hotel,
  Palette,
  Store
} from "lucide-react";

import {
  SoloMotorIcon,
  SoloCarIcon,
  SoloDeliveryIcon,
  SoloFoodIcon,
  SoloCarpoolIcon,
  SoloMarketIcon,
  SoloMartIcon,
  SoloAllServicesIcon,
  SoloIndustryCargoIcon,
  SoloGovPillarIcon,
  SoloCoinStampIcon
} from "@/components/icons";

export interface AppService {
  id: string;
  name: string;
  shortName: string;
  description: string;
  icon: any;
  color: string;
  bgColor: string;
  borderColor: string;
  tag?: string;
  isAvailable: boolean;
  category?: "mobility" | "merchant" | "government" | "industry";
  targetRole?: string;
  additionalRole?: string;
  agencyName?: string;
  estimatedFee?: number;
  feeLabel?: string;
}

// 8 Top Super-App Home Services with Bespoke Hyperlocal Duotone Icons
export const SUPER_APP_SERVICES: AppService[] = [
  {
    id: "ride",
    name: "Ojek Motor",
    shortName: "Ojek",
    description: "Antar jemput cepat tanpa potongan komisi",
    icon: SoloMotorIcon,
    color: "text-emerald-500",
    bgColor: "bg-emerald-500/10 hover:bg-emerald-500/20",
    borderColor: "border-emerald-500/30",
    tag: "Bebas Fee",
    isAvailable: true,
    category: "mobility"
  },
  {
    id: "car",
    name: "Mobil Warga",
    shortName: "Mobil",
    description: "Transportasi roda empat nyaman & hemat",
    icon: SoloCarIcon,
    color: "text-teal-500",
    bgColor: "bg-teal-500/10 hover:bg-teal-500/20",
    borderColor: "border-teal-500/30",
    isAvailable: true,
    category: "mobility"
  },
  {
    id: "send",
    name: "Kirim Kilat",
    shortName: "Kirim",
    description: "Kurir paket & dokumen instan se-Solo",
    icon: SoloDeliveryIcon,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10 hover:bg-blue-500/20",
    borderColor: "border-blue-500/30",
    tag: "Instan",
    isAvailable: true,
    category: "mobility"
  },
  {
    id: "food",
    name: "Kuliner Warga",
    shortName: "Kuliner",
    description: "Pesan makan dari warung UMKM lokal",
    icon: SoloFoodIcon,
    color: "text-orange-500",
    bgColor: "bg-orange-500/10 hover:bg-orange-500/20",
    borderColor: "border-orange-500/30",
    tag: "Enak",
    isAvailable: true,
    category: "merchant"
  },
  {
    id: "titip",
    name: "Titip Tetangga",
    shortName: "Titip",
    description: "Titip pesanan searah rute driver hemat ongkir",
    icon: SoloCarpoolIcon,
    color: "text-amber-500",
    bgColor: "bg-amber-500/10 hover:bg-amber-500/20",
    borderColor: "border-amber-500/30",
    tag: "Hemat 50%",
    isAvailable: true,
    category: "mobility"
  },
  {
    id: "pasar",
    name: "Pasar Warga",
    shortName: "Flash Sale",
    description: "Flash sale stok UMKM diskon radius 2 km",
    icon: SoloMarketIcon,
    color: "text-rose-500",
    bgColor: "bg-rose-500/10 hover:bg-rose-500/20",
    borderColor: "border-rose-500/30",
    tag: "Diskon",
    isAvailable: true,
    category: "merchant"
  },
  {
    id: "mart",
    name: "Apotek & Mart",
    shortName: "Belanja",
    description: "Kebutuhan harian & obat warung tetangga",
    icon: SoloMartIcon,
    color: "text-purple-500",
    bgColor: "bg-purple-500/10 hover:bg-purple-500/20",
    borderColor: "border-purple-500/30",
    isAvailable: true,
    category: "merchant"
  },
  {
    id: "more",
    name: "Semua Layanan",
    shortName: "Lainnya",
    description: "Semua modul ekosistem & layanan dinas kota",
    icon: SoloAllServicesIcon,
    color: "text-slate-500 dark:text-zinc-400",
    bgColor: "bg-zinc-800/80 hover:bg-zinc-800",
    borderColor: "border-zinc-700/60",
    isAvailable: true,
  }
];

// Comprehensive 16-Services Catalog for /services/more
export const ALL_ECOSYSTEM_SERVICES: AppService[] = [
  // -------------------------------------------------------------
  // PILAR 1: MOBILITAS & LOGISTIK
  // -------------------------------------------------------------
  {
    id: "ride",
    name: "Ojek Motor Warga",
    shortName: "Ojek",
    description: "Antar jemput cepat tanpa potongan komisi per trip.",
    icon: SoloMotorIcon,
    color: "text-emerald-500",
    bgColor: "bg-emerald-500/10 hover:bg-emerald-500/20",
    borderColor: "border-emerald-500/30",
    tag: "Bebas Fee",
    isAvailable: true,
    category: "mobility",
    feeLabel: "Mulai Rp 8.000"
  },
  {
    id: "car",
    name: "Mobil Warga Solo",
    shortName: "Mobil",
    description: "Transportasi mobil keluarga nyaman & hemat se-Solo Raya.",
    icon: SoloCarIcon,
    color: "text-teal-500",
    bgColor: "bg-teal-500/10 hover:bg-teal-500/20",
    borderColor: "border-teal-500/30",
    isAvailable: true,
    category: "mobility",
    feeLabel: "Mulai Rp 15.000"
  },
  {
    id: "send",
    name: "Kirim Kilat Dokumen & Paket",
    shortName: "Kirim",
    description: "Kurir instan door-to-door barang belanjaan & berkas penting.",
    icon: SoloDeliveryIcon,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10 hover:bg-blue-500/20",
    borderColor: "border-blue-500/30",
    tag: "Instan",
    isAvailable: true,
    category: "mobility",
    feeLabel: "Mulai Rp 6.000"
  },
  {
    id: "titip",
    name: "Titip Tetangga Searah",
    shortName: "Titip",
    description: "Batching order searah rute driver hemat ongkir hingga 50%.",
    icon: SoloCarpoolIcon,
    color: "text-amber-500",
    bgColor: "bg-amber-500/10 hover:bg-amber-500/20",
    borderColor: "border-amber-500/30",
    tag: "Hemat 50%",
    isAvailable: true,
    category: "mobility",
    feeLabel: "Diskon 50%"
  },
  {
    id: "cargo_truck",
    name: "Sewa Truk & Blind Van Kargo",
    shortName: "Kargo",
    description: "Angkut barang berat, pindahan rumah & pasokan grosir.",
    icon: SoloIndustryCargoIcon,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10 hover:bg-blue-500/20",
    borderColor: "border-blue-500/30",
    tag: "Muatan Berat",
    isAvailable: true,
    category: "industry",
    targetRole: "industry",
    additionalRole: "ind_kargo",
    agencyName: "PT Bengawan Kargo Logistik",
    feeLabel: "Mulai Rp 150.000"
  },

  // -------------------------------------------------------------
  // PILAR 2: PASAR & UMKM LOKAL
  // -------------------------------------------------------------
  {
    id: "food",
    name: "Kuliner Legendaris Warga",
    shortName: "Kuliner",
    description: "Sate Pak Manto, Selat Mbak Lies, Timlo, Es Dawet Telasih.",
    icon: SoloFoodIcon,
    color: "text-orange-500",
    bgColor: "bg-orange-500/10 hover:bg-orange-500/20",
    borderColor: "border-orange-500/30",
    tag: "Solo Enak",
    isAvailable: true,
    category: "merchant",
    targetRole: "merchant",
    additionalRole: "merch_kuliner",
    agencyName: "Sentra Kuliner Khas Surakarta"
  },
  {
    id: "pasar",
    name: "Pasar Tradisional & Sayur Subuh",
    shortName: "Pasar Gede",
    description: "Sayur segar Merbabu, daging, bumbu dapur dari Kios Mbok Darmi.",
    icon: SoloMarketIcon,
    color: "text-rose-500",
    bgColor: "bg-rose-500/10 hover:bg-rose-500/20",
    borderColor: "border-rose-500/30",
    tag: "Segar 04.00",
    isAvailable: true,
    category: "merchant",
    targetRole: "merchant",
    additionalRole: "merch_pasar",
    agencyName: "Pasar Gede & Pasar Legi"
  },
  {
    id: "mart",
    name: "Warung Mart & Apotek Herbal",
    shortName: "Mart",
    description: "Kebutuhan pokok, gas LPG, air galon & jamu tradisional keraton.",
    icon: SoloMartIcon,
    color: "text-purple-500",
    bgColor: "bg-purple-500/10 hover:bg-purple-500/20",
    borderColor: "border-purple-500/30",
    isAvailable: true,
    category: "merchant",
    targetRole: "merchant",
    additionalRole: "merch_mart",
    agencyName: "Jaringan Warung Tetangga"
  },
  {
    id: "batik_craft",
    name: "Batik Laweyan & Seni Triwindu",
    shortName: "Batik",
    description: "Batik tulis, cap, dan kerajinan seni asli perajin Surakarta.",
    icon: Palette,
    color: "text-amber-500",
    bgColor: "bg-amber-500/10 hover:bg-amber-500/20",
    borderColor: "border-amber-500/30",
    tag: "Asli Solo",
    isAvailable: true,
    category: "merchant",
    targetRole: "merchant",
    additionalRole: "merch_batik",
    agencyName: "Sentra Batik Laweyan & Kauman"
  },

  // -------------------------------------------------------------
  // PILAR 3: PROGRAM PUBLIK DINAS PEMKOT SURAKARTA
  // -------------------------------------------------------------
  // --- 1. DISDUKCAPIL ---
  {
    id: "dukcapil_antar_ktp",
    name: "Dukcapil: Antar KTP-el / KK ke Rumah",
    shortName: "Antar KTP",
    description: "Layanan pengantaran dokumen kependudukan resmi langsung ke rumah warga oleh driver mitra.",
    icon: SoloGovPillarIcon,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10 hover:bg-blue-500/20",
    borderColor: "border-blue-500/30",
    tag: "Resmi Pemkot",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_dukcapil",
    agencyName: "Disdukcapil Kota Surakarta",
    feeLabel: "Subsidi Rp 10.000"
  },
  {
    id: "dukcapil_kia_akte",
    name: "Dukcapil: Antar KIA & Akta Kelahiran/Kematian",
    shortName: "KIA & Akta",
    description: "Pengantaran Kartu Identitas Anak dan akta catatan sipil door-to-door bersegel dinas.",
    icon: SoloGovPillarIcon,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10 hover:bg-blue-500/20",
    borderColor: "border-blue-500/30",
    tag: "Catatan Sipil",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_dukcapil",
    agencyName: "Disdukcapil Kota Surakarta",
    feeLabel: "Subsidi Rp 10.000"
  },
  {
    id: "dukcapil_mobile_perekaman",
    name: "Dukcapil: Layanan Perekaman KTP Mobile",
    shortName: "Perekaman Lansia",
    description: "Jemput bola tim Dukcapil bersama driver ke rumah lansia/difabel untuk rekam biometrik.",
    icon: SoloGovPillarIcon,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10 hover:bg-blue-500/20",
    borderColor: "border-blue-500/30",
    tag: "Jemput Bola",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_dukcapil",
    agencyName: "Disdukcapil Kota Surakarta",
    feeLabel: "Gratis Bersyarat"
  },

  // --- 2. DINAS KESEHATAN ---
  {
    id: "dinkes_resep_puskesmas",
    name: "Dinkes: Antar Resep Obat 17 Puskesmas",
    shortName: "Resep Obat",
    description: "Pengantaran obat resep pasien rawat jalan & lansia dari Puskesmas terdekat bersegel steril.",
    icon: Stethoscope,
    color: "text-teal-500",
    bgColor: "bg-teal-500/10 hover:bg-teal-500/20",
    borderColor: "border-teal-500/30",
    tag: "Kesehatan",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_dinkes",
    agencyName: "Dinas Kesehatan Surakarta",
    feeLabel: "Ongkir Koperasi Rp 8.000"
  },
  {
    id: "dinkes_prolanis",
    name: "Dinkes: Antar Obat Rutin Pasien Prolanis BPJS",
    shortName: "Obat Prolanis",
    description: "Distribusi terjadwal obat diabetes & hipertensi bagi pasien rawat jalan kronis di rumah.",
    icon: Stethoscope,
    color: "text-teal-500",
    bgColor: "bg-teal-500/10 hover:bg-teal-500/20",
    borderColor: "border-teal-500/30",
    tag: "Kronis/Lansia",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_dinkes",
    agencyName: "Dinas Kesehatan Surakarta",
    feeLabel: "Subsidi Rp 8.000"
  },
  {
    id: "dinkes_donor_darah",
    name: "Dinkes: Kurir Darah Siaga PMI Surakarta",
    shortName: "Kurir Darah PMI",
    description: "Mobilisasi spesimen kantong darah darurat dari PMI Solo ke rumah sakit faskes rujukan.",
    icon: Stethoscope,
    color: "text-teal-500",
    bgColor: "bg-teal-500/10 hover:bg-teal-500/20",
    borderColor: "border-teal-500/30",
    tag: "Emergency",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_dinkes",
    agencyName: "Dinas Kesehatan Surakarta",
    feeLabel: "Prioritas Cepat"
  },

  // --- 3. DINAS SOSIAL ---
  {
    id: "dinsos_bansos_pasar",
    name: "Dinas Sosial: Voucher Bansos & Tebus Sembako",
    shortName: "Bansos Sembako",
    description: "Klaim kupon beras pasar murah, verifikasi bansos PKH & sembako kios pasar tradisional.",
    icon: HeartHandshake,
    color: "text-rose-500",
    bgColor: "bg-rose-500/10 hover:bg-rose-500/20",
    borderColor: "border-rose-500/30",
    tag: "Bantuan Sosial",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_dinsos",
    agencyName: "Dinas Sosial Kota Surakarta",
    feeLabel: "Gratis Bersyarat"
  },
  {
    id: "dinsos_ojek_difabel",
    name: "Dinas Sosial: Armada Ojek Siaga Difabel & Lansia",
    shortName: "Ojek Difabel",
    description: "Layanan antar-jemput fasilitas kesehatan 100% disubsidi bagi warga difabel & lansia.",
    icon: HeartHandshake,
    color: "text-rose-500",
    bgColor: "bg-rose-500/10 hover:bg-rose-500/20",
    borderColor: "border-rose-500/30",
    tag: "Subsidi 100%",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_dinsos",
    agencyName: "Dinas Sosial Kota Surakarta",
    feeLabel: "Gratis Rp 0"
  },
  {
    id: "dinsos_tanggap_bencana",
    name: "Dinas Sosial: Logistik Dapur Umum & Bencana",
    shortName: "Tagana Bencana",
    description: "Pengiriman logistik sembako cepat dan mobilisasi relawan Tagana ke titik terdampak banjir/kebakaran.",
    icon: HeartHandshake,
    color: "text-rose-500",
    bgColor: "bg-rose-500/10 hover:bg-rose-500/20",
    borderColor: "border-rose-500/30",
    tag: "Siaga Bencana",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_dinsos",
    agencyName: "Dinas Sosial Kota Surakarta",
    feeLabel: "Mobilisasi Kilat"
  },

  // --- 4. DINAS KOPERASI & UMKM ---
  {
    id: "diskop_shu_koperasi",
    name: "Dinas Koperasi: Poin Stamp & SHU Koperasi",
    shortName: "Koperasi SHU",
    description: "Tabungan stamp belanja UMKM, dividen SHU tahunan, dan subsidi karcis harian pengemudi.",
    icon: SoloCoinStampIcon,
    color: "text-emerald-500",
    bgColor: "bg-emerald-500/10 hover:bg-emerald-500/20",
    borderColor: "border-emerald-500/30",
    tag: "Koperasi Warga",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_diskop",
    agencyName: "Dinas Koperasi & UMKM Surakarta",
    feeLabel: "Program Warga"
  },
  {
    id: "diskop_nib_pendampingan",
    name: "Dinas Koperasi: Pendampingan Legalitas NIB OSS",
    shortName: "NIB Usaha Mikro",
    description: "Petugas pendamping dinas turun langsung mendampingi penerbitan izin usaha mikro di kios warga.",
    icon: SoloCoinStampIcon,
    color: "text-emerald-500",
    bgColor: "bg-emerald-500/10 hover:bg-emerald-500/20",
    borderColor: "border-emerald-500/30",
    tag: "Gratis NIB",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_diskop",
    agencyName: "Dinas Koperasi & UMKM Surakarta",
    feeLabel: "Fasilitasi Gratis"
  },
  {
    id: "diskop_modal_bergulir",
    name: "Dinas Koperasi: Fasilitasi Dana Bergulir & Pelatihan",
    shortName: "Dana Bergulir",
    description: "Pendaftaran program inkubasi usaha, pelatihan higienitas kemasan dan dana bergulir UMKM.",
    icon: SoloCoinStampIcon,
    color: "text-emerald-500",
    bgColor: "bg-emerald-500/10 hover:bg-emerald-500/20",
    borderColor: "border-emerald-500/30",
    tag: "Dana Usaha",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_diskop",
    agencyName: "Dinas Koperasi & UMKM Surakarta",
    feeLabel: "Bunga 0%"
  },

  // --- 5. DINAS KEBUDAYAAN & PARIWISATA ---
  {
    id: "dispar_heritage_tour",
    name: "Dinas Pariwisata: Rute Wisata Heritage Solo",
    shortName: "Wisata Solo",
    description: "Paket jelajah Keraton Solo, Pura Mangkunegaran, Museum Radya Pustaka & Pasar Triwindu.",
    icon: Calendar,
    color: "text-amber-500",
    bgColor: "bg-amber-500/10 hover:bg-amber-500/20",
    borderColor: "border-amber-500/30",
    tag: "Budaya",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_dispar",
    agencyName: "Dinas Pariwisata Surakarta",
    feeLabel: "Mulai Rp 35.000"
  },
  {
    id: "dispar_tiket_event",
    name: "Dinas Pariwisata: Kalender Event Budaya & Great Sale",
    shortName: "Event Budaya",
    description: "Jadwal Kirab 1 Suro, Solo Batik Carnival, International Mask Festival & tiket pertunjukan resmi.",
    icon: Calendar,
    color: "text-amber-500",
    bgColor: "bg-amber-500/10 hover:bg-amber-500/20",
    borderColor: "border-amber-500/30",
    tag: "Agenda Budaya",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_dispar",
    agencyName: "Dinas Pariwisata Surakarta",
    feeLabel: "Informasi Publik"
  },
  {
    id: "dispar_pemandu_wisata",
    name: "Dinas Pariwisata: Pemandu Wisata Resmi HPI",
    shortName: "Pemandu HPI",
    description: "Booking pemandu wisata resmi bersertifikat HPI terintegrasi driver penjemputan turis.",
    icon: Calendar,
    color: "text-amber-500",
    bgColor: "bg-amber-500/10 hover:bg-amber-500/20",
    borderColor: "border-amber-500/30",
    tag: "Guide Resmi",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_dispar",
    agencyName: "Dinas Pariwisata Surakarta",
    feeLabel: "Tarif Terstandar"
  },

  // --- 6. DINAS PERHUBUNGAN ---
  {
    id: "dishub_cfd_shelter",
    name: "Dishub: Peta Shelter CFD & Integrasi BST",
    shortName: "CFD & BST",
    description: "Jalur steril Car Free Day Slamet Riyadi, shelter ojek resmi & angkutan feeder Batik Solo Trans.",
    icon: TrafficCone,
    color: "text-yellow-500",
    bgColor: "bg-yellow-500/10 hover:bg-yellow-500/20",
    borderColor: "border-yellow-500/30",
    tag: "Lalu Lintas",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_dishub",
    agencyName: "Dinas Perhubungan Surakarta",
    feeLabel: "Informasi Lalin"
  },
  {
    id: "dishub_lapor_jalan",
    name: "Dishub: Lapor Kemacetan & Lampu Lalin Rusak",
    shortName: "Lapor Lalin",
    description: "Warga dan driver dapat melaporkan pohon tumbang, rambu rusak atau kemacetan seketika.",
    icon: TrafficCone,
    color: "text-yellow-500",
    bgColor: "bg-yellow-500/10 hover:bg-yellow-500/20",
    borderColor: "border-yellow-500/30",
    tag: "Respon Cepat",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_dishub",
    agencyName: "Dinas Perhubungan Surakarta",
    feeLabel: "Layanan Warga"
  },
  {
    id: "dishub_kir_digital",
    name: "Dishub: Antrean Uji KIR & Retribusi Parkir QRIS",
    shortName: "KIR & Parkir",
    description: "Pendaftaran berkala uji KIR kendaraan angkutan barang/penumpang dan struk parkir digital.",
    icon: TrafficCone,
    color: "text-yellow-500",
    bgColor: "bg-yellow-500/10 hover:bg-yellow-500/20",
    borderColor: "border-yellow-500/30",
    tag: "KIR Kendaraan",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_dishub",
    agencyName: "Dinas Perhubungan Surakarta",
    feeLabel: "Sesuai Perda"
  },

  // --- 7. BADAN PENDAPATAN DAERAH (BAPENDA) ---
  {
    id: "bapenda_pbb_online",
    name: "Bapenda: Bayar PBB-P2 Online & Cek SPPT",
    shortName: "Bayar PBB",
    description: "Cek tagihan Pajak Bumi & Bangunan, cetak bukti lunas digital dan bayar instan via QRIS / Wallet.",
    icon: SoloGovPillarIcon,
    color: "text-indigo-500",
    bgColor: "bg-indigo-500/10 hover:bg-indigo-500/20",
    borderColor: "border-indigo-500/30",
    tag: "PAD Solo",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_bapenda",
    agencyName: "Bapenda Kota Surakarta",
    feeLabel: "Bebas Admin"
  },
  {
    id: "bapenda_retribusi_pasar",
    name: "Bapenda: Retribusi Kios Pasar Digital (QRIS)",
    shortName: "Retribusi Pasar",
    description: "Pembayaran e-Retribusi harian pedagang Pasar Gede, Pasar Legi, dan Klewer langsung tercatat di kas daerah.",
    icon: SoloGovPillarIcon,
    color: "text-indigo-500",
    bgColor: "bg-indigo-500/10 hover:bg-indigo-500/20",
    borderColor: "border-indigo-500/30",
    tag: "E-Retribusi",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_bapenda",
    agencyName: "Bapenda Kota Surakarta",
    feeLabel: "Transparan"
  },
  {
    id: "bapenda_konsultasi_insentif",
    name: "Bapenda: Konsultasi Pajak UMKM & Insentif Kepatuhan",
    shortName: "Konsultasi & Poin",
    description: "Dapatkan stamp poin loyalitas bagi wajib pajak taat dan konsultasi gratis NPWPD usaha baru.",
    icon: SoloGovPillarIcon,
    color: "text-indigo-500",
    bgColor: "bg-indigo-500/10 hover:bg-indigo-500/20",
    borderColor: "border-indigo-500/30",
    tag: "Reward Poin",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_bapenda",
    agencyName: "Bapenda Kota Surakarta",
    feeLabel: "Bonus Stamp"
  },

  // --- 8. DINAS PENDIDIKAN ---
  {
    id: "disdik_antar_jemput_sekolah",
    name: "Disdik: Antar Jemput Sekolah Bersubsidi (Zonasi Solo)",
    shortName: "Jemputan Sekolah",
    description: "Transportasi antar-jemput anak sekolah aman dengan driver mitra bersertifikasi anak.",
    icon: SoloGovPillarIcon,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10 hover:bg-blue-500/20",
    borderColor: "border-blue-500/30",
    tag: "Ramah Anak",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_disdik",
    agencyName: "Dinas Pendidikan Surakarta",
    feeLabel: "Subsidi Pendidikan"
  },
  {
    id: "disdik_antar_ijazah_buku",
    name: "Disdik: Antar Legalisir Ijazah & Paket Buku BOS",
    shortName: "Legalisir & Buku",
    description: "Layanan pengantaran berkas legalisir ijazah dan paket buku sekolah door-to-door.",
    icon: SoloGovPillarIcon,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10 hover:bg-blue-500/20",
    borderColor: "border-blue-500/30",
    tag: "Dokumen Siswa",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_disdik",
    agencyName: "Dinas Pendidikan Surakarta",
    feeLabel: "Tarif Koperasi"
  },

  // --- 9. DINAS LINGKUNGAN HIDUP ---
  {
    id: "dlh_jemput_sampah_daur_ulang",
    name: "DLH: Jemput Sampah Daur Ulang Bank Sampah RW",
    shortName: "Bank Sampah",
    description: "Panggil kurir motor/viar untuk timbang & jemput kardus, plastik, dan jelantah ke rumah.",
    icon: SoloGovPillarIcon,
    color: "text-emerald-500",
    bgColor: "bg-emerald-500/10 hover:bg-emerald-500/20",
    borderColor: "border-emerald-500/30",
    tag: "Tukar Jadi Uang",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_dlh",
    agencyName: "Dinas Lingkungan Hidup Surakarta",
    feeLabel: "Dapat Saldo/Poin"
  },
  {
    id: "dlh_lapor_pohon_tumbang",
    name: "DLH: Lapor Pohon Rawan Tumbang & Perantingan",
    shortName: "Perantingan Pohon",
    description: "Pengaduan cepat perantingan pohon peneduh jalan yang membahayakan kabel/warga.",
    icon: SoloGovPillarIcon,
    color: "text-emerald-500",
    bgColor: "bg-emerald-500/10 hover:bg-emerald-500/20",
    borderColor: "border-emerald-500/30",
    tag: "Solo Rindang",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_dlh",
    agencyName: "Dinas Lingkungan Hidup Surakarta",
    feeLabel: "Layanan Gratis"
  },

  // --- 10. DINAS PEMADAM KEBAKARAN & PENYELAMATAN ---
  {
    id: "damkar_panic_button",
    name: "Damkar: Tombol Darurat Kebakaran (Panic GPS)",
    shortName: "Darurat Damkar",
    description: "Sinyal darurat kebakaran seketika dengan transmisi koordinat GPS presisi ke pos Damkar terdekat.",
    icon: SoloGovPillarIcon,
    color: "text-rose-500",
    bgColor: "bg-rose-500/10 hover:bg-rose-500/20",
    borderColor: "border-rose-500/30",
    tag: "Darurat 24 Jam",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_damkar",
    agencyName: "Dinas Damkar Surakarta",
    feeLabel: "Bebas Biaya 100%"
  },
  {
    id: "damkar_animal_rescue",
    name: "Damkar: Animal Rescue & Evakuasi Cincin Darurat",
    shortName: "Animal Rescue",
    description: "Evakuasi sarang tawon vespa, ular masuk rumah, dan pemotongan cincin macet di jari.",
    icon: SoloGovPillarIcon,
    color: "text-rose-500",
    bgColor: "bg-rose-500/10 hover:bg-rose-500/20",
    borderColor: "border-rose-500/30",
    tag: "Rescue Non-Api",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_damkar",
    agencyName: "Dinas Damkar Surakarta",
    feeLabel: "Layanan Sigap"
  },

  // --- 11. DINAS PERPUSTAKAAN & KEARSIPAN ---
  {
    id: "dispusip_kurir_buku",
    name: "Dispusip: Kurir Pustaka (Pinjam & Antar Buku)",
    shortName: "Kurir Pustaka",
    description: "Peminjaman buku fisik koleksi Perpustakaan Kota Solo diantar-jemput ke rumah pembaca.",
    icon: SoloGovPillarIcon,
    color: "text-purple-500",
    bgColor: "bg-purple-500/10 hover:bg-purple-500/20",
    borderColor: "border-purple-500/30",
    tag: "Solo Membaca",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_dispusip",
    agencyName: "Dinas Perpustakaan Surakarta",
    feeLabel: "Ongkir Flat Rp 6.000"
  },

  // --- 12. DINAS KETAHANAN PANGAN & PERTANIAN ---
  {
    id: "dispertan_klinik_hewan_homecare",
    name: "Dispertan: Dokter Hewan Homecare & Vaksin Rabies",
    shortName: "Klinik Hewan",
    description: "Layanan kunjungan dokter hewan Puskeswan Solo untuk pemeriksaan anabul & vaksin rabies.",
    icon: SoloGovPillarIcon,
    color: "text-emerald-500",
    bgColor: "bg-emerald-500/10 hover:bg-emerald-500/20",
    borderColor: "border-emerald-500/30",
    tag: "Puskeswan Solo",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_dispertan",
    agencyName: "Dinas Ketahanan Pangan & Pertanian",
    feeLabel: "Fasilitas Pemkot"
  },

  // --- 13. DINAS TENAGA KERJA & PERINDUSTRIAN ---
  {
    id: "disnaker_kartu_kuning_ak1",
    name: "Disnaker: Antar Fisik Kartu Kuning AK-1 & Kursus BLK",
    shortName: "Kartu Kuning AK1",
    description: "Pengurusan kartu pencari kerja dan pendaftaran kursus barista/las/digital BLK gratis.",
    icon: SoloGovPillarIcon,
    color: "text-orange-500",
    bgColor: "bg-orange-500/10 hover:bg-orange-500/20",
    borderColor: "border-orange-500/30",
    tag: "Karir Warga",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_disnaker",
    agencyName: "Dinas Tenaga Kerja & Perindustrian",
    feeLabel: "Siap Kerja"
  },

  // --- 14. DISKOMINFO & STATISTIK ---
  {
    id: "diskominfo_ulas_terpadu",
    name: "Diskominfo: Kanal Aduan Warga ULAS Surakarta",
    shortName: "Aduan ULAS",
    description: "Kirim laporan dan aduan pelayanan publik ke Unit Layanan Aduan Surakarta (ULAS) terintegrasi.",
    icon: SoloGovPillarIcon,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10 hover:bg-blue-500/20",
    borderColor: "border-blue-500/30",
    tag: "Respon 1x24 Jam",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_diskominfo",
    agencyName: "Diskominfo Kota Surakarta",
    feeLabel: "Layanan Terbuka"
  },

  // --- 15. SATPOL PP ---
  {
    id: "satpolpp_lapor_trantib",
    name: "Satpol PP: Lapor Gangguan Ketertiban & Izin Acara",
    shortName: "Lapor Trantibum",
    description: "Pengaduan kebisingan malam, parkir liar, dan permohonan pengamanan keramaian warga.",
    icon: SoloGovPillarIcon,
    color: "text-slate-500",
    bgColor: "bg-slate-500/10 hover:bg-slate-500/20",
    borderColor: "border-slate-500/30",
    tag: "Trantibum Solo",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_satpolpp",
    agencyName: "Satpol PP Kota Surakarta",
    feeLabel: "Patroli Humanis"
  },

  // --- 16. BPBD SURAKARTA ---
  {
    id: "bpbd_peringatan_dini_banjir",
    name: "BPBD: Radar EWS Bengawan Solo & Bantuan Darurat",
    shortName: "Radar EWS Banjir",
    description: "Status level siaga sungai Bengawan Solo real-time dan permintaan bantuan logistik tenda darurat.",
    icon: SoloGovPillarIcon,
    color: "text-teal-500",
    bgColor: "bg-teal-500/10 hover:bg-teal-500/20",
    borderColor: "border-teal-500/30",
    tag: "Siaga Bencana",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_bpbd",
    agencyName: "BPBD Kota Surakarta",
    feeLabel: "Respon Kilat"
  },

  // --- 17. DP3APM (PERLINDUNGAN ANAK & PEREMPUAN) ---
  {
    id: "dp3a_hotline_sahabat_perempuan",
    name: "DP3APM: Hotline Sahabat Perempuan & Konseling Puspaga",
    shortName: "Hotline PPA",
    description: "Layanan darurat perlindungan tindak kekerasan perempuan/anak & sesi konseling keluarga gratis.",
    icon: SoloGovPillarIcon,
    color: "text-pink-500",
    bgColor: "bg-pink-500/10 hover:bg-pink-500/20",
    borderColor: "border-pink-500/30",
    tag: "Rahasia & Aman",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_dp3a",
    agencyName: "DP3APM Kota Surakarta",
    feeLabel: "Gratis Penuh"
  },

  // --- 18. DPMPTSP (MAL PELAYANAN PUBLIK BALAI KOTA) ---
  {
    id: "dpmptsp_antar_sk_izin",
    name: "DPMPTSP: Antar SK Izin Usaha MPP & Antrean Online",
    shortName: "Izin Usaha MPP",
    description: "Pengantaran fisik SK izin usaha/IMB berstempel basah dari Mal Pelayanan Publik ke alamat kantor.",
    icon: SoloGovPillarIcon,
    color: "text-indigo-500",
    bgColor: "bg-indigo-500/10 hover:bg-indigo-500/20",
    borderColor: "border-indigo-500/30",
    tag: "MPP Sudirman",
    isAvailable: true,
    category: "government",
    targetRole: "government",
    additionalRole: "gov_dpmptsp",
    agencyName: "DPMPTSP Kota Surakarta",
    feeLabel: "Kurir Resmi"
  },

  // -------------------------------------------------------------
  // PILAR 4: LAYANAN INDUSTRI & KESEHATAN TERBUKA UNTUK WARGA
  // -------------------------------------------------------------
  {
    id: "klinik_homecare_lab",
    name: "Klinik Medika: Homecare & Ambil Sampel Lab",
    shortName: "Lab Homecare",
    description: "Booking tenaga medis datang ke rumah untuk cek darah, tensi, dan spesimen laboratorium.",
    icon: FlaskConical,
    color: "text-teal-500",
    bgColor: "bg-teal-500/10 hover:bg-teal-500/20",
    borderColor: "border-teal-500/30",
    tag: "Medis B2B",
    isAvailable: true,
    category: "industry",
    targetRole: "industry",
    additionalRole: "ind_klinik",
    agencyName: "Klinik Pratama & Lab Medika Solo",
    feeLabel: "Mulai Rp 45.000"
  },
  {
    id: "travel_shuttle_balapan",
    name: "Solo Wisata Trans: Shuttle Stasiun / Bandara",
    shortName: "Shuttle",
    description: "Antar-jemput terjadwal Stasiun Balapan, Purwosari & Bandara Adi Soemarmo.",
    icon: Bus,
    color: "text-orange-500",
    bgColor: "bg-orange-500/10 hover:bg-orange-500/20",
    borderColor: "border-orange-500/30",
    tag: "Shuttle Wisata",
    isAvailable: true,
    category: "industry",
    targetRole: "industry",
    additionalRole: "ind_travel",
    agencyName: "Solo Wisata Trans Nusantara",
    feeLabel: "Mulai Rp 25.000"
  }
];
